//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smartlock_backend.Models
{
    using smartlock_backend.DTOS;
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuario()
        {
            this.Acessos = new HashSet<Acessos>();
            this.Fechadura = new HashSet<Fechadura>();
            this.PessoaFisica = new HashSet<PessoaFisica>();
            this.PessoaJuridica = new HashSet<PessoaJuridica>();
            this.Endereco = new HashSet<Endereco>();
            this.FechadurasVInculadas = new HashSet<Fechadura>();
        }
    
        public string RFIDCard { get; set; }
        public string Nome { get; set; }
        public string Senha { get; set; }
        public string Email { get; set; }
        public int UsuarioId { get; set; }
        public string Telefone { get; set; }
        public string Foto { get; set; }
        public int PerfilId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Acessos> Acessos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fechadura> Fechadura { get; set; }
        public virtual Perfil Perfil { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PessoaFisica> PessoaFisica { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PessoaJuridica> PessoaJuridica { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Endereco> Endereco { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fechadura> FechadurasVInculadas { get; set; }

        public DTOVerificaUsuarioVinculado toVerificarUsuarioVinculadoDTO(bool usuarioVinculado)
        {
            DTOVerificaUsuarioVinculado usuarioVerificado = new DTOVerificaUsuarioVinculado()
            {
                RFIDCard = this.RFIDCard,
                Nome = this.Nome,
                Email = this.Email,
                UsuarioId = this.UsuarioId,
                Telefone = this.Telefone,
                Foto = this.Foto,
                PerfilId = this.PerfilId,
                UsuarioVinculado = usuarioVinculado
            };
            return usuarioVerificado;
        }

        public bool usuarioVinculadoAFechadura(Fechadura fechadura)
        {
            return this.FechadurasVInculadas.Contains(fechadura);
        }
    }
}
